### ISSUE TITLE
Master branch suggest old Django version

### ISSUE THREAD

**Issue by ricco386** [sclorg/django-ex#174]
Django 1.11.X LTS is out of support as of April 1, 2020. Branch `2.2.x` seems to have supported version of Django. 

https://www.djangoproject.com/download/

How about switch `2.2.x` to `master`?

**Comment by frenzymadness** [comment]
I'd like to do it but the problem here is that the new Django 2.2.x doesn't work on RHEL/Centos 7 because it requires a newer version of SQLite than we have there. And this example/template is used in many places where Centos/RHEL 7 are still supported so the switch would break a lot of things.

By the way, readme contains info about this. I think there is nothing we can do about it now. What do you think?

**Comment by ricco386** [comment]
Unfortunatelly, I have no idea where is this repo used... I just found it as an example in OpenShift reference for sample Django project.

You can create branch 1.11.x from current master and fix all other Centos/RHEL 7 references to new branch 1.11.x branch. Once that is done you should be able switch the 2.2.x to master... However I have no idea how much work is it... 

Other than that I guess you dont have any other option unless Centos/RHEL 7 is out of support, but thats probably in couple of years (not sure when the 10 years support will end).

**Comment by frenzymadness** [comment]
I've tried that and then I had to revert those changes, see https://github.com/sclorg/django-ex/pull/154 and related PRs.
