### ISSUE TITLE
Example Django apps do not work with FIPS enabled clusters

### ISSUE THREAD

**Issue by mbach04** [sclorg/django-ex#182]
The Django python examples that are populated as quick-starts / examples in an OCP 4.x cluster, will not build on an OpenShift cluster with FIPS enabled.

**Comment by frenzymadness** [comment]
Could you please share more details? What package it needs causes this? Or is this because we use some disabled hash function?

**Comment by frenzymadness** [comment]
Before I start with an investigation, could you please tell me where the problem you see lays? Is the Django example source code not compatible with FIPS or is the problem in the S2I Python container or in its OpenShift configuration?

**Comment by mbach04** [comment]
As soon as I can get another FIPS enabled cluster up I'll dig in deeper. I suspect it's not just the Django code, bc I saw this with other examples as well later on. If you have the time, prompting RHPDS to host FIPS enabled clusters as an option would help. I've requested this one line variable change, but have yet to see any traction.

**Comment by frenzymadness** [comment]
It seems to me that there are only two possible ways to fix this problem: we can either fix Django upstream to be FIPS-compatible or use something else as an example project.

Fixing Django upstream might be possible thanks to the new `usedforsecurity` keyword argument for constructors in hashlib but it's available only in Python 3.9+ and it's hard to predict whether Django developers would be interested in such change.

Using some other project might need a lot of work and time. We already have some of them in s2i python container and some others available as standalone projects on Github like https://github.com/renefs/flask-ex

The point is that we check FIPS-compatibility on RPM level so everything provided as RPM in the images should be compatible. I don't think we have the resources to also make upstream projects FIPS-compatible.

Is this a big issue for you?

**Comment by mbach04** [comment]
If it were merely a project sitting on Github serving as an application example, I would consider this trivial. But, the fact is, upstream or not, we reference this in every cluster as the "Easy Button" for users to get started with applications on OpenShift. Creating something that does not work with FIPS enabled on the cluster blocks a very significant number of users from using it. It turns their first "Easy button" experience with OpenShift into a point of frustration.

**Comment by frenzymadness** [comment]
I completely understand. However, the example is there for quite some time and nobody complained ever since which makes me think about the number of people using FIPS on OpenShift.

But yes, we have to find a solution. Fixing Django is not the way because we can do it only for Python 3.9+ and we also don't know whether they are interested in something like this. Another possibility is to come with a different example.

All I can promise right now is that we will discuss it and I'll let you know. Cc @hhorak

**Comment by pkubatrh** [comment]
Hi @mbach04, sorry for the wait, it a took a while before we were able to discuss this issue inside our team.
The way we see things this example application should be used as demo-material, or intro to how Python applications are used on Openshift. A FIPS-enabled cluster however seems like something that would make more sense to use in production, rather than when just looking at how to set up your application in Openshift using the "easy button".
As a result of this we decided that it does not make much sense to spend time making this example application work on FIPS-enabled clusters and will be closing this issue.

**Comment by mbach04** [comment]
All I would say is that if we support deploying the cluster with a feature turned on, we should support the things that run on top of it with said feature turned on. Usually security controls nerf functionality and there's nothing to be done. In this case, we're setting a standard of security and choosing when to meet it. The concept is shift security left, not kick it down the road.
